imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
  translator:
    fallback: %locale%
  secret: %secret%
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation:
    enable_annotations: true
  templating:
    engines: ['twig']
    assets_version: %version%
  default_locale: %locale%
  trusted_proxies: ~
  session: ~
  fragments: ~
  http_method_override: true

twig:
  debug: %kernel.debug%
  strict_variables: %kernel.debug%
  globals:
    facebook_uri: '%facebook_uri%'
    twitter_uri: '%twitter_uri%'
    youtube_uri: '%youtube_uri%'
  form:
    resources:
      - 'AdcogDefaultBundle::bootstrap.html.twig'

assetic:
  debug: %kernel.debug%
  use_controller: false
  bundles:
    - AdcogDefaultBundle
  filters:
    cssrewrite: ~
    yui_css:
      jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    yui_js:
      jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine:
  dbal:
    driver: %database_driver%
    host: %database_host%
    port: %database_port%
    dbname: %database_name%
    user: %database_user%
    password: %database_password%
    charset: UTF8
  orm:
    auto_generate_proxy_classes: %kernel.debug%
    auto_mapping: true

swiftmailer:
  transport: %mailer_transport%
  host: %mailer_host%
  username: %mailer_user%
  password: %mailer_password%
  spool:
    type: file
    path: %kernel.root_dir%/spool/

liip_imagine:
  resolvers:
    default:
      web_path:
        cache_prefix: cache
  filter_sets:
    cache: ~
    default_20_20:
      quality: 100
      filters:
        thumbnail: {size: [30,30], mode: outbound}
    default_30_30:
      quality: 100
      filters:
        thumbnail: {size: [30,30], mode: outbound}
    default_40_40:
      quality: 100
      filters:
        thumbnail: {size: [40,40], mode: outbound}
    default_150_150:
      quality: 100
      filters:
        thumbnail: {size: [150,150], mode: outbound}
    default_300_200:
      quality: 100
      filters:
        thumbnail: {size: [300,200], mode: outbound}
    default_400_300:
      quality: 100
      filters:
        thumbnail: {size: [400,300], mode: outbound}
    default_800_400:
      quality: 100
      filters:
        thumbnail: {size: [800,400], mode: outbound}

eb_doctrine:
  filesystem:
    depth: 8
  paginator:
    default_limit: 10
    max_limit: 100

eb_translation:
  replace_underscore: true
  track_selected_links: 'active'

eb_email:
  senders:
    -
      name: ADCOG
      email: %mailer_user%
  globals:
    facebook_uri: '%facebook_uri%'
    twitter_uri: '%twitter_uri%'
    youtube_uri: '%youtube_uri%'
    mailer_user: '%mailer_user%'
  images:
    header: '%kernel.root_dir%/../src/Adcog/DefaultBundle/Resources/public/img/mail-header.png'
    footer: '%kernel.root_dir%/../src/Adcog/DefaultBundle/Resources/public/img/mail-footer.png'
    facebook: '%kernel.root_dir%/../src/Adcog/DefaultBundle/Resources/public/img/social/facebook.png'
    twitter: '%kernel.root_dir%/../src/Adcog/DefaultBundle/Resources/public/img/social/twitter.png'
    youtube: '%kernel.root_dir%/../src/Adcog/DefaultBundle/Resources/public/img/social/youtube.png'
    rss: '%kernel.root_dir%/../src/Adcog/DefaultBundle/Resources/public/img/social/rss.png'
  emails:
    contact:
      template: 'AdcogDefaultBundle:Email:contact.html.twig'
      subject: '{{ mail.subject|raw }}'
    user_persist:
      template: 'AdcogDefaultBundle:Email:userPersist.html.twig'
      subject: '{{ user }}, bienvenue sur le site de l''ADCOG'
    user_persist_alert:
      template: 'AdcogDefaultBundle:Email:userPersistAlert.html.twig'
      subject: 'Nouvel utilisateur sur le site : {{ user }}'
    user_password_lost:
      template: 'AdcogDefaultBundle:Email:userPasswordLost.html.twig'
      subject: '{{ user }}, comment récupérer votre mot de passe'
    user_update_email:
      template: 'AdcogDefaultBundle:Email:userUpdateEmail.html.twig'
      subject: '{{ user }}, votre email a changé sur le site de l''ADCOG'
    user_update_password:
      template: 'AdcogDefaultBundle:Email:userUpdatePassword.html.twig'
      subject: '{{ user }}, votre mot de passe a changé sur le site de l''ADCOG'
    email:
      template: 'AdcogDefaultBundle:Email:email.html.twig'
      subject: '{{ subject }}'
    payment_persist:
      template: 'AdcogDefaultBundle:Email:paymentPersist.html.twig'
      subject: 'Votre facture "{{ payment }}" a bien été enregistrée sur le site de l''ADCOG'
    payment_validate:
      template: 'AdcogDefaultBundle:Email:paymentValidate.html.twig'
      subject: 'Votre facture "{{ payment }}" a été validée sur le site de l''ADCOG'
    payment_invalidate:
      template: 'AdcogDefaultBundle:Email:paymentInvalidate.html.twig'
      subject: 'Votre facture "{{ payment }}" a été annulée sur le site de l''ADCOG'
    payment_persist_alert:
      template: 'AdcogDefaultBundle:Email:paymentPersistAlert.html.twig'
      subject: 'Nouvelle adhésion sur le site : {{ payment }}'
    comment_persist_alert:
      template: 'AdcogDefaultBundle:Email:commentPersistAlert.html.twig'
      subject: 'Nouveau commentaire sur le site : {{ comment }}'

#eb_admin:
#  routing:
#    annotation:
#      pattern: '{controller}_{action}'